pipelines/validatePR.yml
Created an azure pipeline.yml file to validate PRs
Fixes #24
=> PR build validation

.gitignore, SamplesDashboard/SamplesDashboard/Controllers/SamplesController.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboard/Services/test.json, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboard/appsettings.json, SamplesDashboard/SamplesDashboardTests/Factories/BaseWebApplicationFactory.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs, SamplesDashboard/SamplesDashboardTests/SamplesDashboardTests.csproj, SamplesDashboard/SamplesDashboardTests/TestStartup.cs, SamplesDashboard/SamplesDashboardTests/testSettings.json
Added dependency Injection and introduced a Data Transfer Object
=> Added Dependency Injection 

SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboard/Startup.cs
Using IHttpClientFactory in our service collection and injecting it into our service instead of creating a new instance each time.
=> Used IHttpClientFactory

SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/Controllers/SamplesController.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs
Added a button that takes a user to the sample repository on Github.
Fixes #46
=> Create 'Go to Repository' button

SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/Models/PackageStatus.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
Created the status function to display a dependency status.
Fixes #40
=> Create status function

pipelines/release.yml
Created the release.yml file for deployment to azure pipeline.
=> Create release.yml file

SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Services/NugetService.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/NugetServiceTests.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
Query nuget for latest versions of packages with unknown values.
Fixes #39
=> Fetch unknown versions from Nuget

SamplesDashboard/SamplesDashboard/Properties/AssemblyInfo.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboardTests/NugetServiceTests.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
=> Update latest versions and status for empty strings

SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Samples.tsx, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
Removing the horizontal bar that displays at the bottom of the DetailsList.
Completing the stars URL.
=> Fix horizontal scrollbar display

SamplesDashboard/SamplesDashboard/ClientApp/src/index.tsx
To prevent delayed changes during deployment =, we opt out of the enabled service worker.
More info here https://stackoverflow.com/questions/49604821/cache-busting-with-cra-react
Please describe the tests that you ran to verify your changes.
Fixes #(issue)
=> Unregister service worker to fix deployment delay

SamplesDashboard/SamplesDashboard/Models/NpmQuery.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/NpmService.cs, SamplesDashboard/SamplesDashboard/Services/NugetService.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/NpmServiceTests.cs, SamplesDashboard/SamplesDashboardTests/NugetServiceTests.cs
Accessing NPM's registry and fetching the latest library versions for the packages in the samples
Fixes #76
=> Fetch npm package versions

SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Samples.tsx, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs, SamplesDashboard/SamplesDashboardTests/testSettings.json
Created a function that returns the highest status in a sample's list of dependencies.
Render the status on the main page.
=> Display status on the main samples dashboard page

SamplesDashboard/SamplesDashboard/ClientApp/package-lock.json, SamplesDashboard/SamplesDashboard/Policies.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
Enabling retry policy in deployment
=> Enable retry policy

SamplesDashboard/SamplesDashboard/Controllers/SamplesController.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Policies.cs, SamplesDashboard/SamplesDashboard/Services/NpmService.cs, SamplesDashboard/SamplesDashboard/Services/SampleService.cs, SamplesDashboard/SamplesDashboardTests/SampleServiceTests.cs
Updating the query to implement pagination and retrieve all the samples within the Microsoft Graph organization
Fixes #81
=> Implement pagination

SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
Fixing the endpoint for fetching repository details
=> Fix endpoint for fetching details

SamplesDashboard/SamplesDashboard/Constants.cs, SamplesDashboard/SamplesDashboard/Controllers/RepositoriesController.cs, SamplesDashboard/SamplesDashboard/HostedServices/RepositoryHostedService.cs, SamplesDashboard/SamplesDashboard/Program.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
Adding hosted services in the background to keep refreshing the cache and ensure its constantly in a warm state
=> Implement cache refreshing 

SamplesDashboard/SamplesDashboard/Controllers/RepositoriesController.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs, SamplesDashboard/SamplesDashboard/Services/NpmService.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/AzureSdkServiceTests.cs
- Created an azure sdk service that downloads an xml file contents and parses them into a dictionary.
-  We then retrieve the azure sdk versions stored in the dictionary and set them on our dependency payload
- Added tests
Fixes #82
=> Fetch azure sdk versions

SamplesDashboard/SamplesDashboard/ClientApp/src/components/layout/NavMenu.css, SamplesDashboard/SamplesDashboard/ClientApp/src/components/layout/NavMenu.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/components/layout/PageTitle.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Repositories.tsx
Multiple changes in place, these include:
* Change in position of the language column to the second last position closer to the Feature Area column.
* Addition of tooltips when you hover over a status cell.
* Change in font sizes on the Navigation bar, tabs and the titles.
* Consistent lower-case used to display repository names and sentence case used to display column headings.
* Addition of a card feature and a darker background colour used.
* Increased margins between the table and the edge of the desktop screen.
Fixes #91 #92  #93  #94  #95
=> Altered views to enhance the UI appearance

SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Repositories.tsx, SamplesDashboard/SamplesDashboard/Controllers/RepositoriesController.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
- Fetching the list of admins for all samples and sdks
- Adding a description of each sample/sdk on the details page
Fixes #99, #98
=> Fetching a list of admins for Each repository

SamplesDashboard/SamplesDashboard/ClientApp/package-lock.json, SamplesDashboard/SamplesDashboard/ClientApp/package.json, SamplesDashboard/SamplesDashboard/ClientApp/src/App.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/components/layout/NavMenu.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx
Added the back button on the Details page.
Fixes #97
=> Add back button 

SamplesDashboard/SamplesDashboard/web.Debug.config, SamplesDashboard/SamplesDashboard/web.Release.config, SamplesDashboard/SamplesDashboard/web.config
Fix the In Process handler load failure when starting the app
=> Fix the InProc Failure when app starts

SamplesDashboard/SamplesDashboard/web.Debug.config, SamplesDashboard/SamplesDashboard/web.Release.config, SamplesDashboard/SamplesDashboard/web.config
Increases maximum url length for the application
Please describe the tests that you ran to verify your changes.
Fixes #(issue)
=> Increase max url length for server

SamplesDashboard/SamplesDashboard/ClientApp/package-lock.json, SamplesDashboard/SamplesDashboard/ClientApp/package.json, SamplesDashboard/SamplesDashboard/ClientApp/src/components/layout/PageTitle.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx
Included status statistics that provide an overview of the status of Sample and SDK repositories in the dashboard.
Fixes #103 #90
=> Add status statistics 

SamplesDashboard/SamplesDashboard/Helper/JWTHelper.cs, SamplesDashboard/SamplesDashboard/MessageHandlers/GithubAuthHandler.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Services/GithubAuthService.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboard/appsettings.json, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs, SamplesDashboard/SamplesDashboardTests/appsettings.json
- Create a GithubApp using octokit
- Install it within MicrosoftGraph organization's account
- Use the installation token to fetch views and contributors fields
- Populate said data on UI
=> Create GithubApp and use it to Fetch views and Contributors

SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.Styles.js, SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.Styles.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.Styles.js, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.Styles.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx
- Adjusting the heights of the statistics cards
- Remove repetitive details on the stats card footer
- Align text to the center of the cards
- Rephrase the page titles for the details page
=> Making UI adjustments

SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx
Change the filter placeholder back to a label for accessibility purposes
Please describe the tests that you ran to verify your changes.
=> Putting a filter label for accessibility issues

SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
Fixing the missing Language and Feature area bug by adding a delimiter parameter for splitting the yaml header on a newline character
Fixes #127
=> Fix missing language and feature area bug

SamplesDashboard/SamplesDashboard/Services/NugetService.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboardTests/NugetServiceTests.cs
Update the latest version column for preview versions to display the latest non-preview versions
Original version:
Updated version:
Fixes #132
=> Fix preview versions for non-preview current library versions

SamplesDashboard/SamplesDashboard/ClientApp/src/custom.css, SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx, SamplesDashboard/SamplesDashboard/Models/PackageStatus.cs, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
Change computation for an urgent update status to represent specific libraries with security alerts
Sorting
Fixes #128 , #135
=> Fix urgent update and Status sorting issue

SamplesDashboard/.vscode/launch.json, SamplesDashboard/.vscode/tasks.json, SamplesDashboard/SamplesDashboard/ClientApp/src/types/samples.ts, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx, SamplesDashboard/SamplesDashboard/ClientApp/tsconfig.json, SamplesDashboard/SamplesDashboard/Properties/serviceDependencies.json, SamplesDashboard/SamplesDashboard/Properties/serviceDependencies.local.json, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs
Add a filter by Owner field to allow sample and sdk owners to search for specific samples that they own
Fixes #129
=> Filter by owner column

README.md, SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx, SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs, SamplesDashboard/SamplesDashboard/Models/YamlHeader.cs, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, SamplesDashboard/SamplesDashboard/Services/CocoaPodsService.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboard/Startup.cs, SamplesDashboard/SamplesDashboardTests/CocoaPodsServiceTests.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
- Added ability to parse dependencies in a Podfile for iOS projects (requires devx.yml file in repo pointing to Podfile)
- Added ability to flag a repo as having no dependencies so dashboard can consider it "up to date"
- Updated details page to be consistent with repository list page
- Added new tests `ShouldGetDependenciesFromPodfile` and `ShouldGetCocoaPodsVersions`
=> New Features

SamplesDashboard/SamplesDashboard/Constants.cs, SamplesDashboard/SamplesDashboard/Models/MavenQuery.cs, SamplesDashboard/SamplesDashboard/Services/MavenService.cs, SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs, SamplesDashboard/SamplesDashboardTests/MavenServiceTests.cs, SamplesDashboard/SamplesDashboardTests/RepositoriesServiceTests.cs
Improved Java dependency processing:
- Added check to Google's Maven repository for version information. Previously the dashboard couldn't get version information on Android dependencies since they aren't listed in maven.org
- Changed service to query Maven for pom.xml dependencies. Previously this relied on GitHub's provided version information which was hit-or-miss
See new tests in MavenServiceTests.cs and RepositoriesServiceTests.cs
=> Java improvements

SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx
Updates the path to security alerts
=> Update the link to security alerts

SamplesDashboard/SamplesDashboard/ClientApp/package-lock.json, SamplesDashboard/SamplesDashboard/ClientApp/package.json, SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx, SamplesDashboard/SamplesDashboard/SamplesDashboard.csproj, pipelines/release.yml, pipelines/validatePR.yml
This PR updates the master branch with latest changes in dev
=> Merges dev to master

SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs
Updated scope value for Microsoft Open Source Service. Their team contacted me to let me know they are retiring the old app ID for their service.
=> Updated scope value for Microsoft Open Source Service
